const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Relax in a peaceful beachfront cottage with stunning ocean views.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stylish loft in the heart of the city, perfect for urban living.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Cabin Retreat",
    description: "Escape to a cozy cabin surrounded by mountains and nature.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: 900,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Luxury Villa with Pool",
    description: "Spacious villa with private pool and modern amenities.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 3000,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Rustic Countryside House",
    description: "Charming house in the countryside with beautiful landscapes.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 800,
    location: "Tuscany",
    country: "Italy",
  },
  {
    title: "Lakeview Apartment",
    description: "Enjoy stunning lake views from this modern apartment.",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    price: 1100,
    location: "Zurich",
    country: "Switzerland",
  },
  {
    title: "Desert Safari Camp",
    description: "Experience the desert lifestyle in a luxury camp.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: 700,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Paris Studio Apartment",
    description: "Cozy studio in the heart of Paris near iconic landmarks.",
    image: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade",
    price: 1300,
    location: "Paris",
    country: "France",
  },
  {
    title: "Seaside Bungalow",
    description: "A small bungalow just steps away from the beach.",
    image: "https://images.unsplash.com/photo-1493558103817-58b2924bce98",
    price: 1000,
    location: "Goa",
    country: "India",
  },
  {
    title: "Forest Treehouse",
    description: "Stay in a magical treehouse surrounded by forest.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    price: 600,
    location: "Kerala",
    country: "India",
  },
  {
    title: "Penthouse with Skyline View",
    description: "Luxury penthouse with stunning skyline views.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 4000,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Budget Backpacker Hostel",
    description: "Affordable hostel for travelers and backpackers.",
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5",
    price: 200,
    location: "Bangkok",
    country: "Thailand",
  },
  {
    title: "Snowy Ski Resort Chalet",
    description: "Perfect stay for ski lovers in snowy mountains.",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    price: 1800,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "Island Hut Stay",
    description: "Simple hut stay on a beautiful tropical island.",
    image: "https://images.unsplash.com/photo-1506929562872-bb421503ef21",
    price: 500,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Modern Glass House",
    description: "Minimalist glass house surrounded by nature.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 2200,
    location: "California",
    country: "United States",
  },
  {
    title: "Historic Castle Stay",
    description: "Stay in a real medieval castle with modern comfort.",
    image: "https://images.unsplash.com/photo-1501183638710-841dd1904471",
    price: 3500,
    location: "Edinburgh",
    country: "Scotland",
  },
  {
    title: "City Center Condo",
    description: "Convenient condo located in city center.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    price: 1000,
    location: "Toronto",
    country: "Canada",
  },
  {
    title: "Cliffside Villa",
    description: "Villa on cliff with breathtaking ocean view.",
    image: "https://images.unsplash.com/photo-1505692794403-55b2a6d7b5c4",
    price: 2700,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Eco Friendly Farm Stay",
    description: "Live sustainably on a farm with organic food.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b",
    price: 600,
    location: "Punjab",
    country: "India",
  },
  {
    title: "Studio Near Tech Hub",
    description: "Perfect for professionals working in tech hubs.",
    image: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5",
    price: 1400,
    location: "Bangalore",
    country: "India",
  }
];

module.exports = sampleListings;